# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service1_pb2 as service1__pb2


class Service1Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddNumbers = channel.unary_unary(
        '/Service1/AddNumbers',
        request_serializer=service1__pb2.Numbers.SerializeToString,
        response_deserializer=service1__pb2.Result.FromString,
        )
    self.ProcessImg = channel.unary_unary(
        '/Service1/ProcessImg',
        request_serializer=service1__pb2.ImgInput.SerializeToString,
        response_deserializer=service1__pb2.ImgOutput.FromString,
        )


class Service1Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddNumbers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessImg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Service1Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.AddNumbers,
          request_deserializer=service1__pb2.Numbers.FromString,
          response_serializer=service1__pb2.Result.SerializeToString,
      ),
      'ProcessImg': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessImg,
          request_deserializer=service1__pb2.ImgInput.FromString,
          response_serializer=service1__pb2.ImgOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Service1', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
