# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service1.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservice1.proto\"\x1f\n\x07Numbers\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\x13\n\x06Result\x12\t\n\x01z\x18\x03 \x01(\x03\"\x17\n\x08ImgInput\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"*\n\tImgOutput\x12\r\n\x05width\x18\x01 \x01(\x02\x12\x0e\n\x06height\x18\x02 \x01(\x02\x32T\n\x08Service1\x12!\n\nAddNumbers\x12\x08.Numbers\x1a\x07.Result\"\x00\x12%\n\nProcessImg\x12\t.ImgInput\x1a\n.ImgOutput\"\x00\x62\x06proto3')
)




_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Numbers.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Numbers.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='z', full_name='Result.z', index=0,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=70,
)


_IMGINPUT = _descriptor.Descriptor(
  name='ImgInput',
  full_name='ImgInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='ImgInput.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=95,
)


_IMGOUTPUT = _descriptor.Descriptor(
  name='ImgOutput',
  full_name='ImgOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ImgOutput.width', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ImgOutput.height', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['ImgInput'] = _IMGINPUT
DESCRIPTOR.message_types_by_name['ImgOutput'] = _IMGOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERS,
  '__module__' : 'service1_pb2'
  # @@protoc_insertion_point(class_scope:Numbers)
  })
_sym_db.RegisterMessage(Numbers)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'service1_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

ImgInput = _reflection.GeneratedProtocolMessageType('ImgInput', (_message.Message,), {
  'DESCRIPTOR' : _IMGINPUT,
  '__module__' : 'service1_pb2'
  # @@protoc_insertion_point(class_scope:ImgInput)
  })
_sym_db.RegisterMessage(ImgInput)

ImgOutput = _reflection.GeneratedProtocolMessageType('ImgOutput', (_message.Message,), {
  'DESCRIPTOR' : _IMGOUTPUT,
  '__module__' : 'service1_pb2'
  # @@protoc_insertion_point(class_scope:ImgOutput)
  })
_sym_db.RegisterMessage(ImgOutput)



_SERVICE1 = _descriptor.ServiceDescriptor(
  name='Service1',
  full_name='Service1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=141,
  serialized_end=225,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddNumbers',
    full_name='Service1.AddNumbers',
    index=0,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessImg',
    full_name='Service1.ProcessImg',
    index=1,
    containing_service=None,
    input_type=_IMGINPUT,
    output_type=_IMGOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE1)

DESCRIPTOR.services_by_name['Service1'] = _SERVICE1

# @@protoc_insertion_point(module_scope)
